# Google Cloud Build configuration for automated deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zapnote-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zapnote-backend:latest'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/zapnote-backend:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/zapnote-backend:latest'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zapnote-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zapnote-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/zapnote-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/zapnote-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
